### PR TITLE
Rewrote to use better programming techniques and make more compatible

### PR DESCRIPTION
**Pull request by testsnake**

### CODE REVIEW

**Comment by vixen256** [comment]
Eat complete shit dickface

**Comment by vixen256** [comment]
Changing the fucking license

**Comment by testsnake** [comment]
me when

**Comment by vixen256** [comment]
Some actual comments
-Changing the license is bad
-No need for a code of conduct, this isnt some massive community project
-Don't pretend these changes make it better, they cause it to be less readable in some cases
--For example the spacing between functions being incredibly inconsistent
--Or the write memory functions, which just introduce more bloat
--Or the way you write nops
-You've just introduced bugs, like not properly patching pv db switch causing you to require a loose file(you patched this, after I talked about it in pdm2, shouldve been easily caught beforehand)
-You've made it unbuildable on linux and only with MSVC
-The changed names of some functions are incorrect
-Calling samyuu a scrub is incredibly bad form, even worse now youve got a code of conduct
-Calling your fork "ps4_but_good" is incredibly vain
-Config.toml shouldnt be in the source, it should be in a dist folder as its not a source file
-Sig scans are useless at this point in development as it is in development
-The extra lines for hooks cause it to be harder to read than the simple INSTALL_HOOK macro
-Dont change the style, theres a predefined way of doing it with the clang format file
-This needs additional dependencies in the form of the minhook dll which arent present here or linked, incredibly bad form

**Pull request closed without merging**
